name: Release

on:
  release:
    type: [created]

jobs:
  unit-testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install
      - name: run tests
        run: yarn test

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - unit-testing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Packages
        run: yarn install
      - name: Build page
        run: yarn run build --verbose
        env:
          CI: false
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
